apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-pipeline-samples
  tags:
    - python-pipeline
  branch: develop
  harnessData:
    qa_versions:
      - ng-manager_1.29
      - pipeline-service_1.67
    qa_fix_versions: fixVersion ~ '*ng-manager*1.29*' OR fixVersion ~ '*pipeline-service*1.67*'
  annotations:
    backstage.io/techdocs-ref: dir:.
    jira/project-key: IDP
    jenkins.io/github-folder: 'CDS-68313'
    firehydrant.com/service-name: 'python-pipeline-samples'
    # backstage.io/kubernetes-label-selector: 'app=idp-ui'
    backstage.io/kubernetes-namespace: 'harness-delegate-qa'
    backstage.io/source-location: url:https://github.com/vigneswara-propelo/python-pipeline-samples/tree/main/
    github.com/project-slug: vigneswara-propelo/python-pipeline-samples
    pagerduty.com/service-id: PT5ED69
    harness.io/cd-serviceId: idpapp
    harness.io/pipelines: |
      Build: https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/home/orgs/default/projects/IDP_UI/pipelines/Build_IDP_UI_App/pipeline-studio/?storeType=INLINE
      Lint: https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/home/orgs/default/projects/IDP_UI/pipelines/Lint/pipeline-studio
      TypeCheck: https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/home/orgs/default/projects/IDP_UI/pipelines/Typecheck/pipeline-studio
    grafana/dashboard-selector: "(tags @> 'prometheus' || tags @> 'blackbox')"
    npm_token: npm_adfevegevef

spec:
  type: service
  lifecycle: experimental
  owner: harness_account_all_users
  providesApis: 
    - idp-Service-api
