apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-pipeline-samples-1
  tags:
    - python-pipeline
  annotations:
    backstage.io/techdocs-ref: dir:.
#     harness.io/project-url: https://qa.harness.io/ng/account/zEaak-FLS425IEO7OLzMUg/home/orgs/default/projects/vigneshproject/details
#     circleci.com/project-slug: github/vigneswara-propelo/python-pipeline-samples
    gitlab.com/project-id: '43877214'
    jira/project-key: IDP
    jenkins.io/github-folder: 'CDS-68313'
    firehydrant.com/service-name: 'python-pipeline-samples'
    backstage.io/kubernetes-label-selector: 'app=idp-ui'
    backstage.io/kubernetes-namespace: 'invalid'
    github.com/project-slug: vigneswara-propelo/python-pipeline-samples
    pagerduty.com/service-id: PT5ED69
    accountIdentifier: <+account.identifier>
    orgIdentifier: <+variable.account.orgIdentifier>
    projectIdentifier: <+variable.account.projectIdentifier>
    url: https://laxmiharness.pr2.harness.io/ng/account/<+account.identifier>/idp-admin/orgs/<+variable.account.orgIdentifier>/projects/<+variable.account.projectIdentifier>/pipelines/GitHub_Repo_Onboarding/pipeline-studio/?storeType=INLINE&stageId=IDP&sectionId=EXECUTION
    harness.io/pipelines: |
      Build: https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/home/orgs/default/projects/IDP_UI/pipelines/Build_IDP_UI_App/pipeline-studio/?storeType=INLINE
      Lint: https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/home/orgs/default/projects/IDP_UI/pipelines/Lint/pipeline-studio
      TypeCheck: https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/home/orgs/default/projects/IDP_UI/pipelines/Typecheck/pipeline-studio
    grafana/dashboard-selector: "(tags @> 'prometheus' || tags @> 'blackbox')"
    npm_token: npm_adfevegevef

#     snyk.io/org-name: vigneswara-propelo
#     snyk.io/project-ids: 7c7766e6-1231-4e4f-b51f-0cbd2aacb227
spec:
  type: service
  lifecycle: experimental
  owner: aman+pop@harness.io
  providesApis: 
    - idp-Service-api
